import { User } from './user';
// Generated by https://quicktype.io

export interface CommentType {
  url: string;
  html_url: string;
  issue_url: string;
  id: number;
  node_id: string;
  user: User;
  created_at: string;
  updated_at: string;
  author_association: string;
  body: string;
}
