// Generated by https://quicktype.io

export interface LabelType {
  id: number;
  node_id: string;
  url: string;
  name: string;
  color: string;
  default: boolean;
  issues: {
    totalCount: number;
  };
}
